### ISSUE TITLE
Pushing sigtest 2.4 to maven central?

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck-tools#157]
2.4 is in staging now for over a month. Shouldn't we push it to central?

https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/tck/sigtest-maven-plugin/2.4/

**Comment by scottmarlow** [comment]
From the output of the LIST_REPOS command, I see we need to release `jakartatck-1106` as that represents sigtest 2.4 so started that.

**Comment by scottmarlow** [comment]
Now available via https://repo1.maven.org/maven2/jakarta/tck/sigtest-maven-plugin/2.4/
