### ISSUE TITLE
com.sun.tdk.signaturetest.Version is not being updated

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck-tools#33]
This class has several constants that are not being updated by the build as expected by this class. Right now the 2.3 release indicates it is version 2.2. 

```java
public class Version {

    private static I18NResourceBundle i18n =
            I18NResourceBundle.getBundleForClass(Version.class);

    // the following constatnts should be filled in by the build script
    public static final String Number="2.2";
    public static final String build_time="";
    public static final String build_os="";
    public static final String build_user="";
...
```

There is not direct support for filtering java source files in maven, so one would have to use something like the [templating-maven-plugin](https://www.mojohaus.org/templating-maven-plugin/examples/source-filtering.html) and move the com.sun.tdk.signaturetest.Version into a src/main/java-templates directory based on the example configuration.

**Comment by dmatej** [comment]
They could be also moved to a manifest file or a property file and then loaded automatically.
