### ISSUE TITLE
Introduce `-IgnoreJDKClasses` option for ignoring JDK classes and treat (legacy) `-IgnoreJDKClass [jdkclass]` option the same as `-IgnoreJDKClasses`

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck-tools#39]
If `-IgnoreJDKClasses` is specified, JDK classes will be ignored when testing/checking signatures. 

With this change, we will also treat the following options the same as `-IgnoreJDKClasses`:
- IgnoreJDKClass javax.blah
- IgnoreJDKClass

Migration note:  Change from `-IgnoreJDKClass` (or `-IgnoreJDKClass className` sequences) to only specify `-IgnoreJDKClasses`.

**Comment by scottmarlow** [comment]
I'm thinking that we will release a new sigtest release that ignores the `IgnoreJDKClass` (whether java class names are specified after or or not).  Will see if that is possible.

**Comment by jamezp** [comment]
FWIW I don't think we should remove the `-IgnoreJDKClass`, we just re-introduce the old behavior removed in #30. The same approach for #30 could be used, but instead of using `-IgnoreJDKClass` we should use `-IgnoreJDKClasses`.
