### ISSUE TITLE
Integrate the tck-rewrite-ant into the tck-rewrite-tools module

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck-tools#44]
We need to figure out how to ant parser deployment api into the openrewrite rules.

The pattern we should follow is to create a new subclass of the EE10 TCK class per vehicle. If there is no vehicle there is just one subclass.

Right now there is a template to generate the deployment method. We can also create a template that generates the class if the test method name to override are provided.

**Comment by scottmarlow** [comment]
> The pattern we should follow is to create a new subclass of the EE10 TCK class per vehicle. If there is no vehicle there is just one subclass.

This makes sense, will do.

**Comment by scottmarlow** [comment]
Closing as the initial recipe changes are merged via https://github.com/eclipse-ee4j/jakartaee-tck-tools/pull/68
